/*  QBuzz
This sketch demonstrates the QBuzz.  It makes a tone generated by the value
of an ArduSensor.

The parts from Qtechknow that you will need are:
-ArduSensor
-QBuzz

made on 10 July 12
created by Quin
*/

int lowVal = 0;       // declare the lowVal of your ArduSensor 
int highVal = 1023;  // declare the highVal of your ArduSensor

const int QBuzzPin = 11;  // the pin that your QBuzz is connected to
const int ArduSensorPin = A0;  // the pin that your ArduSensor is connected to

void setup() {
  // no need for any code here
}

void loop() {
  // read the ArduSensor
  int sensorValue=analogRead(ArduSensorPin);
  
  // convert the ArduSensor values to values that the QBuzz can use
  int val=map(sensorValue, highVal, lowVal, 150, 1500);  
  
  // make the tone
  tone(QBuzzPin, val);
}

